#! /bin/sh

PORT=''

TARGET=`grep HOSTN sdkconfig.defaults | sed -e 's/^.*="//;s/"//;s/atomspectra-gw-//'`
if [ ."$1" != ."" ] ; then
	TARGET="$1"
fi
echo target: $TARGET

if [ ."$TARGET" = ."n15" ] ; then
	PORT=/dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D029186-if00
fi

if [ ."$TARGET" = ."gs" ] ; then
	PORT=/dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D036896-if00
fi

if [ -n "$TARGET" -a -e "$TARGET" ] ; then
	PORT="$TARGET"
fi

if [ -z "$PORT" -a  -e /dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D036896-if00 ] ; then	# spectra-gs
	PORT=/dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D036896-if00
fi

if [ -z "$PORT" -a  -e /dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D029186-if00 ] ; then	# spectra-n15
	PORT=/dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D029186-if00
fi

if [ -z "$PORT" -a  -e /dev/ttyACM0 ] ; then
	PORT=/dev/ttyACM0
fi

exec minicom -D ${PORT} -b 115200
