#! /usr/bin/bash

. "/home/bag/.espressif/tools/activate_idf_v5.4.4.sh"

PORT=''


if [ ."$1" = ."n15" ] ; then
	PORT=/dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D029186-if00
fi

if [ ."$1" = ."gs" ] ; then
	PORT=/dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D036896-if00
fi

if [ -n "$1" -a -e "$1" ] ; then
	PORT="$1"
fi

if [ -z "$PORT" -a  -e /dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D036896-if00 ] ; then	# spectra-gs
	PORT=/dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D036896-if00
fi

if [ -z "$PORT" -a  -e /dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D029186-if00 ] ; then	# spectra-n15
	PORT=/dev/serial/by-id/usb-1a86_USB_Single_Serial_5C4D029186-if00
fi

if [ -z "$PORT" -a  -e /dev/ttyACM0 ] ; then
	PORT=/dev/ttyACM0
fi


time idf.py -p ${PORT} flash


